### ISSUE TITLE
Duplication Errors : node_modules

### ISSUE THREAD

**Issue by mustafa96m** [ilansas/react-native-navigation-drawer#16]
Please don't include 'node_modules' in the repo it causes duplication error I had to delete it to run react-native run-android.

**Comment by MajeedThaikas** [comment]
I also have the same exact problems 
Duplicate module name: String.prototype.es6

**Comment by Gnuelch** [comment]
propably the same thing, my complete error message in node.js is as follows: (***** being my app root path)

> Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
> error: bundling failed: ambiguous resolution: module `*****\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:
>   * `*****\node_modules\react-native-navigation-drawer\node_modules\react-native\package.json`
>   * `*****\node_modules\react-native\package.json`

deleting `react-native-navigation-drawer\node_modules` alone doesn't resolve it, i also need to clear the cache with `npm start -- --reset-cache`.


Now i'm having an error resolving `var Dimensions = require('Dimensions')` in `react-native-navigation-drawer\index.js` on line 11.
